version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  ### create user?

  # TIME??? TIME??? TIME??? TIME???
  # TIME??? TIME??? TIME??? TIME???
  # TIME??? TIME??? TIME??? TIME???
  #db-1  | 2024-08-09 06:18:37.013 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
  #db-1  | 2024-08-09 06:18:37.015 UTC [43] LOG:  database system was shut down at 2024-08-09 06:18:36 UTC
  #db-1  | 2024-08-09 06:18:37.017 UTC [40] LOG:  database system is ready to accept connections



  app:
    image: letstock:none
    environment:
       SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  ### health check?

