### auth mail
POST http://localhost:8080/code/mail
Content-Type: application/json

{
  "email": "bnbnac@naver.com"
}

### verify
POST http://localhost:8080/code/mail/verification
Content-Type: application/json

{
  "email": "bnbnac@naver.com",
  "code": "79193391"
}

### signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "bnbnac@naver.com",
  "password": "1234",
  "name": "hello",
  "profileImage": "imgurl",
  "greetings": "hi there",
  "code": "79193391"
}

### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com",
  "password": "1234"
}

### logout
DELETE http://localhost:8080/auth/logout
Content-Type: application/json

### test2
GET http://localhost:8080/notauth/test
Content-Type: application/json