### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com",
  "password": "1234"
}

### comment
POST http://localhost:8080/comments/1
Content-Type: application/json

{
  "content": "hello comment"
}
