### auth mail
POST http://localhost:8080/code/mail
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com123"
}

### verify
POST http://localhost:8080/code/mail/verification
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com",
  "code": "78619971"
}

### signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com",
  "password": "1234",
  "name": "hello",
  "profileImage": "imgurl",
  "greetings": "hi there",
  "code": "78619971"
}

### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "seongjin0000@gmail.com",
  "password": "1234"
}

### test
GET http://localhost:8080/auth/test
Content-Type: application/json